- hosts: webServers
  become: true
  vars:
    packageNames:
      - php
      - httpd
  tasks:
    - name: installing packages "{{ packageNames }}"
      package:
       state: present
       name: "{{ packageNames }}"

    - name: starting and enablinng services
      service:
        name: httpd
        state: reloaded
        enabled: true

    - name: copying php OR document dir files
      template:
        src: /var/www/html/index.php
        dest: /var/www/html/index.php

