- hosts: servers
  vars:
    packageName: 
      - "haproxy"
  tasks:
    - name: installing  " {{ packageName }}" httpd 
      package:
        name : "{{ packageName }}"

    - name: emabling haproxy 
      service:
        name: "haproxy"
        state: reloaded
        enabled: true

    - name: disable firewalld by exposing the port to the public
      command: firewall-cmd --zone=public --add-port=5000/tcp --permanent


    - name: copying loadBalancer haproxy.cfg file
      template:
        src: /root/haproxy/server.js
        dest: /root/harproxy.js
